name: sized_context_example
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.2.2"

dependencies:
  flutter:
    sdk: flutter

  universal_platform:
    path: ../

flutter:
  uses-material-design: true
