name: universal_platform
description: Replacement for dart.io.Platform class which works on Web as well as Desktop and Mobile. Allows platform checks in your view/model layer easily.
version: 1.0.0-nullsafety
homepage: https://github.com/gskinnerTeam/flutter-universal-platform

environment:
  sdk: ">=2.19.0 <3.2.2"

dependencies:
